name: Continuous Deployment - Run Azure Login with OIDC

on:
  push:
permissions:
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Run tests
        run: mvn test
      - name: Generate Docker image
        run: mvn spring-boot:build-image \
          --DskipTests \
          --Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/anuncios:latest
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/anuncios:latest

        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
            - name: 'Az CLI login'
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: 'Run az commands to deploy container'
              run: |
                az container create \
                  --resource-group ${{ secrets.AZURE_GROUP }} \
                  --name anuncios \
                  --image ${{ secrets.DOCKERHUB_USERNAME }}/anuncios:latest \
                  --dns-name-label ais-anuncios \
                  --ports 8080